### ISSUE TITLE
Move ViewModels inside the Sidekick project

### ISSUE THREAD

**Issue by leMicin** [domialex/Sidekick#325]
I am encountering random exceptions like this one, when I am running the application.
```
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (This type of CollectionView does not support changes to its SourceCollection from a thread different from the Dispatcher thread.)
 ---> System.NotSupportedException: This type of CollectionView does not support changes to its SourceCollection from a thread different from the Dispatcher thread.
   at System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at Sidekick.UI.Helpers.AsyncObservableCollection`1.RaiseCollectionChanged(Object param) in G:\Repos\Sidekick\src\Sidekick.UI\Helpers\AsyncObservableCollection.cs:line 39
   at Sidekick.UI.Helpers.AsyncObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e) in G:\Repos\Sidekick\src\Sidekick.UI\Helpers\AsyncObservableCollection.cs:line 27
   at System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item)
   at System.Collections.ObjectModel.Collection`1.Add(T item)
   at Sidekick.UI.Prices.PriceViewModel.InitializeMods(List`1 mods) in G:\Repos\Sidekick\src\Sidekick.UI\Prices\PriceViewModel.cs:line 209
   at Sidekick.UI.Prices.PriceViewModel.InitializeFilters() in G:\Repos\Sidekick\src\Sidekick.UI\Prices\PriceViewModel.cs:line 163
   at Sidekick.UI.Prices.PriceViewModel.Initialize() in G:\Repos\Sidekick\src\Sidekick.UI\Prices\PriceViewModel.cs:line 91
   --- End of inner exception stack trace ---
```

Adding a Dispatcher.Invoke() around where I am modifying the collection would fix the issue. It would also probably fix some random crashes that we see sometimes popping off as issues.

The Dispatcher class is a Windows specific class and would therefore not allow cross platform, which is why, we may be better off removing the UI project and moving the code inside the Sidekick project directly.

I would like your thoughts on this.

**Comment by Blinke** [comment]
I'm for consolidating the UI stuff into the main project. If we go cross platform in the future we'd have to adjust a lot of the existing UI related code anyway, both views and view models.

**Comment by leMicin** [comment]
Yeah, the business is really cross platform.
I might have aimed too high with cross platform view models.

**Comment by leMicin** [comment]
@domialex @pobiega Do you have feedback on this? I might want work on this later and then release 0.7.2 later today. Thanks!

**Comment by domialex** [comment]
I think it's a good idea, since it's bound to Windows and in my opinion would make it simpler to understand and maintain.
