### ISSUE TITLE
Crash on update after restart

### ISSUE THREAD

**Issue by Silentguard** [domialex/Sidekick#375]
```
2020-05-04 20:20:22.097 +08:00 [INF] Fetching Trade API Listings from Query jvm2r7lTX.
2020-05-04 20:20:40.152 +08:00 [FTL] Unhandled exception in application root
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Sidekick.Views.Prices.PriceViewModel.LoadMoreData()
   at Sidekick.Views.Prices.PriceViewModel.UpdateQuery()
   at Sidekick.Views.Prices.PriceViewModel.Initialize()
   --- End of inner exception stack trace ---
2020-05-04 20:20:48.667 +08:00 [INF] Changed active language support to English.
2020-05-04 20:20:51.985 +08:00 [DBG] 0% - Checking for Updates... UpdateManager
2020-05-04 20:20:55.393 +08:00 [DBG] 0% - Initializer - Start Reset KeybindEvents
2020-05-04 20:20:55.399 +08:00 [DBG] 0% - Initializer - End Reset KeybindEvents
2020-05-04 20:20:55.399 +08:00 [DBG] 0% - Initializer - Start Reset NativeKeyboard
2020-05-04 20:20:55.400 +08:00 [DBG] 0% - Initializer - End Reset NativeKeyboard
2020-05-04 20:20:55.404 +08:00 [DBG] 0% - Initializer - Start Init StatDataService
2020-05-04 20:20:55.410 +08:00 [INF] Fetching attributes started.
```

**Comment by domialex** [comment]
Did you just update to 0.7.2? It's been released for a while. Can you try to re-download it manually and extract in another folder?

**Comment by Silentguard** [comment]
So i just figured out that process after first restart and crash wasn't terminated. Terminating solved the issue. 

Also i didn't get any sing about second instance running, except odd second log file appearence with name Sidekick_Log20200504_001. Now after success launch old log has been deleted.

**Comment by domialex** [comment]
It's true that there's no message warning that there is an instance already running.
