### ISSUE TITLE
Constant crashing since last update

### ISSUE THREAD

**Issue by Occy74** [domialex/Sidekick#413]
Last part of errorlog:

2020-06-21 22:31:27.464 +02:00 [FTL] Unhandled exception in application root
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Keyword "Alt" is not valid.)
 ---> System.ArgumentException: Keyword "Alt" is not valid.
   at System.Windows.Forms.SendKeys.ParseKeys(String keys, IntPtr hwnd)
   at System.Windows.Forms.SendKeys.Send(String keys, Control control, Boolean wait)
   at System.Windows.Forms.SendKeys.SendWait(String keys, Control control)
   at System.Windows.Forms.SendKeys.SendWait(String keys)
   at Sidekick.Natives.NativeKeyboard.SendInput(String input)
   at Sidekick.Natives.KeybindEvents.<>c__DisplayClass58_0.<<SendInputIf>b__0>d.MoveNext()
   --- End of inner exception stack trace ---

**Comment by leMicin** [comment]
I will have a fix for this soon, but in the meantime, I would suggest not using Alt for keybinds. Sorry.

I've been enjoying the league. I will try to make a patch for some of the bugs tomorrow. Thanks for the feedback.
