### ISSUE TITLE
Sidekick does not start when launching - network issues 

### ISSUE THREAD

**Issue by as69-github** [domialex/Sidekick#484]
Hi, 
i was having an issue with Sidekick the last couple of days.
The app did not start, just said something like "an error occured, cannot start".
I had to look at the logfiles and found that today, the first message seems to be related to a not working http connection.
As i was playing a bit around with my Windows 10 recently and used the Internet Explorer to change proxy settings (chrome is my default browser and uses different/its own proxy settings) i found out that i still had a test proxy (which is basically a VM which is down at the moment) configured. Was very hard to find out, because i was not aware that Sidekick uses Windows Proxy settings. 

Maybe you can add a more speaking error message to the UI itself or implement some kind of error exception so that the application starts, but tells you to check the internet connectivity or something like that.

Here´s my logilfe: 
- at 19:23:14.765 was the first start today
- at 19:26:27.266 was the second start, not even saying something about the network error (just "Unhandled exception in application root")
- at 19:37:31.919 i started it again after changing my proxy settings in IE to a correct value and the application started correctly

```
2020-11-06 19:23:14.765 +01:00 [INF] Changed active language support to English.
2020-11-06 19:23:15.406 +01:00 [DBG] 0% - Checking for Updates... UpdateManager
2020-11-06 19:23:36.677 +01:00 [FTL] Unhandled exception in application root
System.Net.Http.HttpRequestException: Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat.
 ---> System.Net.Sockets.SocketException (10060): Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.EstablishProxyTunnel(HttpRequestHeaders headers, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Sidekick.Core.Update.UpdateManager.GetLatestRelease()
   at Sidekick.Core.Update.UpdateManager.NewVersionAvailable()
   at Sidekick.App.RunAutoUpdate()
   at Sidekick.App.OnStartup(StartupEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2020-11-06 19:26:04.435 +01:00 [FTL] Unhandled exception in application root
System.NullReferenceException: Object reference not set to an instance of an object.
   at Sidekick.Views.Settings.SettingsViewModel..ctor(IUILanguageProvider uiLanguageProvider, SidekickSettings sidekickSettings, INativeKeyboard nativeKeyboard, ILeagueDataService leagueDataService, IKeybindEvents keybindEvents, ICacheService cacheService, IInitializer initializer)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Sidekick.Views.ViewInstance..ctor(IServiceScope scope, Type viewType)
   at Sidekick.Views.ViewLocator.Open[TView]()
   at Sidekick.Views.TrayIcon.TrayIconViewModel.<get_ShowSettingsCommand>b__5_0(Object _)
   at Sidekick.Views.TrayIcon.RelayCommand.Execute(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2020-11-06 19:26:27.266 +01:00 [INF] Changed active language support to English.
2020-11-06 19:26:27.699 +01:00 [DBG] 0% - Checking for Updates... UpdateManager
2020-11-06 19:26:33.875 +01:00 [DBG] WindowService : Getting data for about
2020-11-06 19:26:41.842 +01:00 [FTL] Unhandled exception in application root
System.NullReferenceException: Object reference not set to an instance of an object.
   at Sidekick.Views.Settings.SettingsViewModel..ctor(IUILanguageProvider uiLanguageProvider, SidekickSettings sidekickSettings, INativeKeyboard nativeKeyboard, ILeagueDataService leagueDataService, IKeybindEvents keybindEvents, ICacheService cacheService, IInitializer initializer)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Sidekick.Views.ViewInstance..ctor(IServiceScope scope, Type viewType)
   at Sidekick.Views.ViewLocator.Open[TView]()
   at Sidekick.Views.TrayIcon.TrayIconViewModel.<get_ShowSettingsCommand>b__5_0(Object _)
   at Sidekick.Views.TrayIcon.RelayCommand.Execute(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2020-11-06 19:26:44.913 +01:00 [DBG] WindowService : Saved data for about. Width: 720, Height: 640
2020-11-06 19:37:31.919 +01:00 [INF] Changed active language support to English.
2020-11-06 19:37:32.523 +01:00 [DBG] 0% - Checking for Updates... UpdateManager
2020-11-06 19:37:33.744 +01:00 [DBG] 0% - Initializer - Start Reset KeybindEvents
2020-11-06 19:37:33.752 +01:00 [DBG] 0% - Initializer - End Reset KeybindEvents
2020-11-06 19:37:33.752 +01:00 [DBG] 0% - Initializer - Start Reset NativeKeyboard
2020-11-06 19:37:33.753 +01:00 [DBG] 0% - Initializer - End Reset NativeKeyboard
2020-11-06 19:37:33.755 +01:00 [DBG] 0% - Initializer - Start Before Init LeagueDataService
2020-11-06 19:37:33.758 +01:00 [INF] Fetching leagues started.
2020-11-06 19:37:34.295 +01:00 [INF] 4 leagues fetched.
2020-11-06 19:37:34.312 +01:00 [DBG] 7% - Initializer - End Before Init LeagueDataService
2020-11-06 19:37:34.315 +01:00 [DBG] 7% - Initializer - Start Init StatDataService
2020-11-06 19:37:34.322 +01:00 [DBG] CacheService : Getting data for StatDataService.OnInit
2020-11-06 19:37:34.969 +01:00 [DBG] 15% - Initializer - End Init StatDataService
2020-11-06 19:37:34.969 +01:00 [DBG] 15% - Initializer - Start Init ItemDataService
2020-11-06 19:37:34.971 +01:00 [DBG] CacheService : Getting data for ItemDataService.OnInit
2020-11-06 19:37:35.055 +01:00 [DBG] 23% - Initializer - End Init ItemDataService
2020-11-06 19:37:35.055 +01:00 [DBG] 23% - Initializer - Start Init PseudoStatDataService
2020-11-06 19:37:35.060 +01:00 [INF] Pseudo stat service initialization started.
2020-11-06 19:37:35.060 +01:00 [DBG] CacheService : Getting data for PseudoStatDataService.OnInit
2020-11-06 19:37:35.107 +01:00 [INF] 9 attributes fetched.
2020-11-06 19:37:35.261 +01:00 [DBG] 30% - Initializer - End Init PseudoStatDataService
2020-11-06 19:37:35.261 +01:00 [DBG] 30% - Initializer - Start Init StaticDataService
2020-11-06 19:37:35.263 +01:00 [DBG] CacheService : Getting data for StaticDataService.OnInit
2020-11-06 19:37:35.272 +01:00 [DBG] 38% - Initializer - End Init StaticDataService
2020-11-06 19:37:35.273 +01:00 [DBG] 38% - Initializer - Start Init UILanguageProvider
2020-11-06 19:37:35.274 +01:00 [DBG] 46% - Initializer - End Init UILanguageProvider
2020-11-06 19:37:35.275 +01:00 [DBG] 46% - Initializer - Start After Init ItemDataService
2020-11-06 19:37:35.276 +01:00 [DBG] 53% - Initializer - End After Init ItemDataService
2020-11-06 19:37:35.276 +01:00 [DBG] 53% - Initializer - Start After Init PoeNinjaClient
2020-11-06 19:37:35.276 +01:00 [DBG] 61% - Initializer - End After Init PoeNinjaClient
2020-11-06 19:37:35.276 +01:00 [DBG] 61% - Initializer - Start After Init PoeNinjaCache
2020-11-06 19:37:35.278 +01:00 [INF] Populating PoeNinja cache.
2020-11-06 19:37:37.574 +01:00 [INF] PoeNinja cache populated.
2020-11-06 19:37:37.575 +01:00 [DBG] 69% - Initializer - End After Init PoeNinjaCache
2020-11-06 19:37:37.576 +01:00 [DBG] 69% - Initializer - Start After Init ParserPatterns
2020-11-06 19:37:37.580 +01:00 [DBG] 76% - Initializer - End After Init ParserPatterns
2020-11-06 19:37:37.580 +01:00 [DBG] 76% - Initializer - Start After Init KeybindEvents
2020-11-06 19:37:37.582 +01:00 [DBG] 84% - Initializer - End After Init KeybindEvents
2020-11-06 19:37:37.582 +01:00 [DBG] 84% - Initializer - Start After Init NativeKeyboard
2020-11-06 19:37:37.582 +01:00 [DBG] 92% - Initializer - End After Init NativeKeyboard
2020-11-06 19:37:37.582 +01:00 [DBG] 92% - Initializer - Start After Init NativeProcess
2020-11-06 19:37:37.583 +01:00 [DBG] 100% - Initializer - End After Init NativeProcess
```

**Comment by domialex** [comment]
Sidekick doesn't do anything special in order to access the internet, any other program that made external http calls would probably timeout like it did in this case.
But in this case I would expect the usual message `A fatal error occured during initialization! This might be because the Path of Exile API service is down. Please try again later.`
I'll look into it.

**Comment by leMicin** [comment]
Possibly related to #432 ?

**Comment by leMicin** [comment]
Possibly fixed with the new initialization process of version 1.2.0 . If the issue still occurs after, open a new issue.
